data:
    dataset: "CIFAR10"
    image_size: 32
    channels: 3
    logit_transform: false
    uniform_dequantization: false
    gaussian_dequantization: false
    random_flip: true
    rescaled: true
    num_workers: 4

model:
    type: "dit_x"
    in_channels: 3
    patch_size: 2
    hidden_size: 384
    depth: 12
    num_heads: 6
    mlp_ratio: 4.0
    learn_sigma: False

    var_type: fixedlarge
    ema_rate: 0.9999
    ema: True

diffusion:
    beta_schedule: cosine
    beta_start: 0.0001  # unused
    beta_end: 0.02  # unused
    num_diffusion_timesteps: 4000

training:
    batch_size: 128
    n_epochs: 10000
    n_iters: 5000000
    snapshot_freq: 10000
    validation_freq: 2000

sampling:
    batch_size: 36
    last_only: True

optim:
    weight_decay: 0.001
    optimizer: "AdamW"
    lr: 0.0002
    beta1: 0.9
    amsgrad: false
    eps: 0.00000001
    grad_clip: 1.0
