data:
    dataset: "CIFAR10"
    image_size: 32
    channels: 3
    logit_transform: false
    uniform_dequantization: false
    gaussian_dequantization: false
    random_flip: true
    rescaled: true
    num_workers: 4

model:
    type: "pretrain_mae"
    in_channels: 3
    patch_size: 2
    encoder:
        embed_dim: 384
        depth: 12
        num_heads: 6
    decoder:
        embed_dim: 384
        depth: 12
        num_heads: 6

    dropout: 0.1
    mlp_ratio: 4